# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
bioc_required: true

warnings_are_errors: true

apt_packages:
 - libnetcdf-dev
 - netcdf-bin
 - libopenbabel-dev
 - mesa-common-dev
 - libglu1-mesa-dev

r:
 - release
 - devel

r_github_packages:
  - thomasp85/patchwork
  - aberHRML/binneR
  - jasenfinch/metabolyseR
  - jasenfinch/profilePro
  - jasenfinch/mzAnnotation
  - jasenfinch/MFassign
 
notifications:
    email:
    on_success: change
    on_failure: change
