# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

warnings_are_errors: true

r:
 - release
 - devel
 
 r_github_packages:
    - jasenfinch/metabolyseR
    - jasenfinch/profilePro
 
notifications:
    email:
    on_success: change
    on_failure: change
