# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
bioc_required: true

warnings_are_errors: true

apt_packages:
 - libnetcdf-dev
 - netcdf-bin

r:
 - release
 - devel

bioc_packages:
 - impute

r_github_packages:
  - jasenfinch/metabolyseR
  - jasenfinch/profilePro
 
notifications:
    email:
    on_success: change
    on_failure: change
